backend:
  name: github
  # specify your github repo
  repo: wasd0109/personal-blog
  # lets store all changes related to our publishing activity in a corresponding git-branch
  branch: publishing
# specify our media storage folder (for images)
media_folder: content/assets
# specify path to stored media in PUBLISHED website
public_folder: ../assets # (src for uploaded images will start 'assets/')
# initialize our collections
collections:
  # mine collection called 'Blogs'
  - name: blogs
    label: Blogs
    # folder to store blogs articles at
    folder: content/blogs
    # allow user to create new blog
    create: true
    # fields for each blog
    fields:
      - { name: title, label: Title }
      - { name: excerpt, label: Excerpt }
      - { name: hashtags, label: Hashtags }
      - { name: thumbnail, label: Thumbnail, widget: image }
      - { name: body, label: Body, widget: markdown }
      - { name: date, label: Date, widget: datetime }

  - name: projects
    label: Projects
    # folder to store projects at
    folder: content/projects
    # allow user to create new projects
    create: true
    # fields for each projects
    slug:
    fields:
      - { name: name, label: Name }
      - { name: description, label: description }
      - { name: thumbnail, label: Thumbnail, widget: image }
      - { name: stack, label: Stack }
      - { name: linkToRepo, label: Link to repo }
      - { name: linkToDeploy, label: Link to deploy }
      - { name: date, label: Date, widget: datetime }
